layer.solid = minecraft:red_stained_glass_pane minecraft:orange_stained_glass_pane minecraft:brown_stained_glass_pane minecraft:white_stained_glass_pane minecraft:cyan_stained_glass_pane minecraft:magenta_stained_glass_pane minecraft:pink_stained_glass_pane minecraft:yellow_stained_glass_pane
layer.cutout = minecraft:purple_stained_glass_pane hearthfire:burlap_sack
layer.cutout_mipped = conquest:mossy_sandstone_debris conquest:mossy_sandstone_debris_layer
layer.translucent = 
disableSolidCheck = true