tiles = 1-25
method=repeat
width = 5
height = 5
matchTiles=conquest:textures/block/1_basic_refined/1_stone/1_clay/roman_clay_brick
connectTiles=conquest:textures/block/1_basic_refined/1_stone/1_clay/roman_clay_brick
