tiles=1-8
method=repeat
width=4
height=2
orient=texture
matchBlocks=conquest:apple_wood_plank_boards:facing=west conquest:apple_wood_plank_boards:facing=east
matchTiles=conquest:textures/block/1_basic_refined/3_wood/apple_wood_planks